### ISSUE TITLE
Apollo-graphql-express

### ISSUE THREAD

**Issue by snaplesec** [flash-oss/graphql-upload-minimal#6] opened 2021-04-22 20:37 UTC
With apollo-graphql-express, can I just use the middleware graphql-uploadExpress?  I was using graphql-upload, and could never get it to work when uploading a file, I would get a POST error, missing body-parser?

So I'm just trying to find out how to install it. This looks great as it is much smaller.

Thanks,
Steve

**Comment by koresar** [comment] 2021-04-23 02:07
Hello @snaplesec 
I'm not quite sure what this issue is about. But let me try answering both your questions.
1) Yes
2) I didn't get this question.

Since this is not a bug report I'm going to close this issue. Please ask a more specific question in Discussions: https://github.com/flash-oss/graphql-upload-minimal/discussions

**Closed by koresar** 2021-04-23 02:07 UTC
